### PR TITLE
Glued evaluation, currently disabled

### PR DESCRIPTION
**Pull request by mikeshulman**
Glued evaluation seems to work (it passes all the tests), but it's very slow on large benchmarks.  It appears to be doing excessive memory allocation.  Unfortunately OCaml 5 doesn't yet have memory profiling tools, so I haven't been able to find the culprit; so glued evaluation is currently disabled by an internal flag.  But I'm going to merge this to master anyway, so that the code can be kept up to date with future changes in hopes of fixing it later.

### CODE REVIEW

**Comment by mikeshulman** [comment]
(Glued evaluation is due to Andras Kovacs and is explained [here](https://github.com/AndrasKovacs/smalltt?tab=readme-ov-file#glued-evaluation).)

**Comment by jonsterling** [comment]
Very interesting. I wonder if there is some subtle aspect depending on Haskell's laziness (beyond the suspensions used here) that the performance of smalltt is depending on. Wonder if @andraskovacs has any thoughts.

**Comment by mikeshulman** [comment]
I suspect it's just a dumb choice I'm making somewhere that causing unnecessary traversal and reallocation.  I already found one issue like that.

**Comment by jonsterling** [comment]
> I'd be pretty surprised if there were something you could do with Haskell's laziness that you couldn't also do, at least up to a constant factor, with OCaml's laziness, if you knew exactly what to do.

Definitely agree. Knowing exactly what to do can be a little tricky because Haskell laziness has so many hard-to-predict effects... But I am very confident there should be a way to make this equally performant, or better.

**Comment by mikeshulman** [comment]
It may require some thinking about how to incorporate the degeneracy actions of HOTT/dTT/etc. in a sufficiently lazy way.  The previous performance issue was mainly due to the fact that the degeneracy actions were traversing and rebuilding terms a lot even when the degeneracy was the identity so that no actual work was being done.  There's also some room for folding some more of the nontrivial degeneracy actions into the evaluator that I haven't done yet.  I don't expect that specifically to help with the problems here, but it seems likely to me that something of the same sort is going on.

**Pull request merged**
