### PR TITLE
Add dependencies to dune-project

### PR DESCRIPTION
**Pull request by olynch**
This creates a dune-project file with dependencies for narya.

The file `narya.opam` is generated from the `dune-project` file. I think it makes sense to check this in so that contributors can install the dependencies with `opam install . --deps-only` as normal, rather than having to run `dune build` first. We just have to remember to regenerate it when editing `dune-project`.

### CODE REVIEW

**Comment by olynch** [comment]
> Thanks.  What do you mean by "as normal"?  My experience is that most packages come with build instructions, so we could just tell people to run `dune build` first.  (I really dislike VCing autogenerated files...)

As in, this is what I've seen people typically do. It's fine imo to make people run `dune build` first, it's just a bit awkward because it will fail, so people might get confused.

**Comment by olynch** [comment]
Ah, reading the dune documentation https://dune.readthedocs.io/en/stable/howto/opam-file-generation.html:

> From now on, commands like dune build and dune runtest are going to regenerate the contents of opam files from the metadata in (package) stanzas. If you only want to generate the opam file, run dune build <project_name>.opam.

So an appropriate workflow that will not throw errors is:

```
opam install dune
dune build narya.opam
opam install . --deps-only
dune build
```

I'll remove the .opam file then.

**Comment by mikeshulman** [comment]
Thanks!  We should also update the build instructions in the README, then.

**Comment by olynch** [comment]
Done!

**Comment by olynch** [comment]
@mikeshulman are there any additional things I should take care of for this?

**Comment by mikeshulman** [comment]
Nope, this is good!  Sorry, it's a busy time of year.  Thanks for your patience.

**Pull request merged**
